<a href="https://colab.research.google.com/github/anusartch/COS3109_week1/blob/main/COS3109_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro to Python**

## 1. Hello World

In [ ]:
# Never mind this statement, for compatibility reasons
from __future__ import absolute_import, division, print_function, unicode_literals

print("Hello World")

Hello World


## 2. Function, Conditionals, and Iteration

### Function and Condition

In [ ]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x + y

In [ ]:
print(HelloWorldXY(1, 2))

Hello World, x was < 10
3


### Iteration

In [ ]:
for i in range(8, 25, 5): # i=8, 13, 18, 23 (start, stop, step)
  print("--- Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


## 3. Various kinds of loops starting at 0 to 2

In [ ]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
  print(i)

Iterate over the items. `range(2)` is like a list [0,1].
0
1


In [ ]:
print("Iterate over an actual list.")
for i in [0,1]:
  print(i)

Iterate over an actual list.
0
1


In [ ]:
print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

While works
0
1


## 4. Numpy and lists

**Numpy** as np is the fundamental package for scientific computing with Python.

**Lists (Array)** are data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each
element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes,
lists are defined by having values between square brackets [ ].

In [ ]:
sea_creatures = ['shark', 'cuttlefish', 'squid', 'mantis shrimp', 'anemone']

In [ ]:
sea_creatures[0] = 'sharkkk'
sea_creatures[2] = 'squiddd'
sea_creatures[4] = 'anemoneee'

print(sea_creatures)

['sharkkk', 'cuttlefish', 'squiddd', 'mantis shrimp', 'anemoneee']


### Create a numpy array, and append an element

In [ ]:
import numpy as np # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!


In [ ]:
print("Printing each element and their index")
for i, e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


### Some basic math on arrays

In [ ]:
print("Showing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))

Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


### Type and Dimension

In [ ]:
print("You can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))

You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [ ]:
print("Use numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)

Use numpy to create a [3,3] dimension array with random number
[[0.02014352 0.94289343 0.05811778]
 [0.77160084 0.20405656 0.48281183]
 [0.40296585 0.1680607  0.36253883]]


In [ ]:
print("You can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))

You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


## 5. Linux commands

In [ ]:
print("Doing !ls on filesystem")
!ls -l
!pwd

Doing !ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Jul 13 13:43 sample_data
/content


In [ ]:
print("Install numpy") # Just for test, numpy is actually preinstalled in all Colab instancs
!pip install numpy

Install numpy
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# **Exercise**

## 1. Colab: Create a code cell underneath this text cell and add code to:
- List the path of the current directory (pwd)
- Go to / (cd) and list the content (ls-l)

In [ ]:
!pwd

/content


In [ ]:
!cd /content
!ls -l

total 4
drwxr-xr-x 1 root root 4096 Jul 13 13:43 sample_data


## 2. Python lists without Numpy: Print the second item in the fruits list:

In [10]:
fruits = ["apple", "banana", "cherry"]

print(fruits[1])

banana


## 3. Change the value from “apple” to “kiwi”, in the fruits list:

In [11]:
fruits[0] = "kiwi"

print(fruits)

['kiwi', 'banana', 'cherry']


## 4. Use the append method to add “orange” to the fruits list:

In [12]:
fruits.append("orange")

print(fruits)

['kiwi', 'banana', 'cherry', 'orange']


## 5. Use the insert method to add “lemon” as the second item in the fruits list:

In [13]:
fruits.insert(1, "lemon")

print(fruits)

['kiwi', 'lemon', 'banana', 'cherry', 'orange']


## 6. Use the remove method to delete “banana” from the fruits list:

In [14]:
fruits.remove("banana")

print(fruits)

['kiwi', 'lemon', 'cherry', 'orange']


## 7. Python If...Else: Print “Hello World” if a is greater than b:

In [17]:
a = 50
b = 10
c = 20
d = 20

if a > b:
  print("Hello World")

Hello World


## 8. Print “Hello World” if a is not equal to b:

In [18]:
if a != b:
  print("Hello World")

Hello World


## 9. Print “Yes” if a is equal to b, otherwise print “No”:

In [19]:
if a == b:
  print("Yes")
else:
  print("No")

No


## 10. Print “1” if a is equal to b, print “2” if a is greater than b, otherwise print “3”:

In [20]:
if a == b:
  print("1")
elif a > b:
  print("2")
else:
  print("3")

2


## 11. Print “Hello” if a is equal to b, and c is equal to d:

In [21]:
if a == b and c == d:
  print("Hello")

## 12. Print “Hello” if either a is equal to b, or c is equal to d:

In [23]:
if a == b or c == d:
  print("Hello")

Hello


## 13. Python Loops: Print i as long as i is less than 6:

In [25]:
for i in range(6):
  print(i)

0
1
2
3
4
5


## 14. From #13 stop the loop if i is 3:

In [7]:
for i in range(6):
  if i == 3:
    break
  print(i)

print("\nLoop stop because i is {}".format(i))

0
1
2

Loop stop because i is 3
